name: cFS Documentation and Guides Script

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # 10:45 PM UTC every Sunday
    - cron:  '45 22 * * 0'

jobs:
  # Checks for duplicate actions. Skips push actions if there is a matching or
  # duplicate pull-request action.
  checks-for-duplicates:
    runs-on: ${{ github.repository_owner == 'cFS' && 'linux' || 'ubuntu-latest' }}
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  checkout-and-cache:
    name: Custom checkout and cache for cFS documents
    needs: checks-for-duplicates
    if: ${{ needs.checks-for-duplicates.outputs.should_skip != 'true' || contains(github.ref, 'main') }}
    runs-on: ${{ github.repository_owner == 'cFS' && 'linux' || 'ubuntu-latest' }}

    steps:
      - name: Checkout bundle
        uses: actions/checkout@v3
        with:
          repository: arielswalker/cFS
          submodules: true

      - name: Checkout submodule
        uses: actions/checkout@v3
        with:
          path: cfe

      - name: Cache Source and Build
        id: cache-src-bld
        uses: actions/cache@v3
        with:
          path: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/*
          key: cfs-doc-${{ github.run_number }}

  build-docs:
    needs: checkout-and-cache
    name: Build cFE and Mission Docs
    runs-on: ${{ github.repository_owner == 'cFS' && 'linux' || 'ubuntu-latest' }}
    strategy:
      matrix:
        target: ['cfe-usersguide', 'mission-doc']
    env:
      CACHE_KEY: "cfs-doc-${{ github.run_number }}"
      DEPLOY: "true"
  # DEPLOY: true
  # echo "BUILD_PDF=${{ github.event_name == 'push' && contains(github.ref, 'main') }}" >> $GITHUB_ENV
      APP_NAME: ""
      NEEDS_OSAL_API: "true"
      
    steps:
      - name: Get cache if supplied
        id: cache-src-bld
        if: ${{ env.CACHE_KEY != '' }}
        uses: actions/cache@v4
        with:
          path: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/*
          key: ${{ env.CACHE_KEY }}
          
      - name: Set Build PDF Variable
        id: set-build-pdf
        run: |
          if [ "${{ matrix.target }}" == "cfe-usersguide" ]; then
            echo "BUILD_PDF=true" >> $GITHUB_ENV
          else
            echo "BUILD_PDF=false" >> $GITHUB_ENV
          fi
          
      - name: Set Target Variable
        id: set-target
        run: |
          if [ "${{ matrix.target }}" == "cfe-usersguide" ]; then
            echo "TARGET=[\"cfe-usersguide\"]" >> $GITHUB_ENV
          elif [ "${{ matrix.target }}" == "mission-doc" ]; then
            echo "TARGET=[\"mission-doc\"]" >> $GITHUB_ENV
          fi

      - name: Run Build Document Script
        run: |
          chmod +x ./.github/scripts/build-deploy-doc.sh
          ./.github/scripts/build-deploy-doc.sh "$TARGET" "$CACHE_KEY" "$DEPLOY" "$BUILD_PDF" "$APP_NAME" "$NEEDS_OSAL_API"

      - name: Archive Document Build Logs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}_doc_build_logs
          path: |
            ${{ matrix.target }}_stdout.txt
            ${{ matrix.target }}_stderr.txt
            ${{ matrix.target }}-warnings.log
        
      - name: Archive PDF
        if: ${{ env.BUILD_PDF == true }} 
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}_pdf
          path: ${{ matrix.target }}.pdf

      - name: Deploy to GitHub
        if: ${{ (github.event_name == 'push' && contains(github.ref, 'refs/heads/main')) || (env.BUILD_PDF == 'true' && env.DEPLOY == 'true') }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: deploy
          SINGLE_COMMIT: true
